baseURL = "https://vblanes.github.io/"
languageCode = "es"
title = "S.S. Aleph"
theme = "minimal"
publishDir = "docs"

[params]
    author = "Vicent Blanes"
    description = "Programación, Ciencia y Linux"
    githubUsername = "vblanes"
    accent = "#007fff"
    showBorder = true
    backgroundColor = "#f5f0f0"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/links"
    name = "Links"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:viblasel @ gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vblanes/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/vicent_bdslab/"
    name = "fab fa-twitter"
    weight = 3
[[menu.icon]]
    url="https://www.goodreads.com/user/show/40572650-ravn"
    name = "fas fa-book-reader"
    weight = 4